In [1]:
import pandas as pd

pd.set_option("display.max_columns", 200)

In [3]:
df = pd.read_csv("../data/processed/judicial_decisions_merged_lags_dejure.csv")

print(df.shape)
df.head()

(1077, 264)

,v1,country,iso3,year,de_jure,weighted_de_jure,pos_total,neg_total,de_jure_count_c,de_jure_count_govprot,de_jure_count_i,de_jure_count_p,weighted_de_jure_count_c,weighted_de_jure_count_govprot,weighted_de_jure_count_i,weighted_de_jure_count_p,de_jure_c,de_jure_govprot,de_jure_i,de_jure_p,weighted_de_jure_c,weighted_de_jure_govprot,weighted_de_jure_i,weighted_de_jure_p,pos_sum_c,pos_sum_govprot,pos_sum_i,pos_sum_p,neg_sum_c,neg_sum_govprot,neg_sum_i,neg_sum_p,legal_rule_count_c,legal_rule_count_govprot,legal_rule_count_i,legal_rule_count_p,de_jure_total,weighted_de_jure_total,legal_rule_count_total,de_jure_count_expression,de_jure_count_obligation,weighted_de_jure_count_expressio,weighted_de_jure_count_obligatio,de_jure_expression,de_jure_obligation,weighted_de_jure_expression,weighted_de_jure_obligation,pos_sum_expression,pos_sum_obligation,neg_sum_expression,neg_sum_obligation,legal_rule_count_expression,legal_rule_count_obligation,appeal_nonreg,appeal_nonreg_crisis,appeal_reg,appeal_reg_crisis,c_disinfo_gen,c_disinfo_gen_crisis,c_disinfo_gen_digi,c_disinfo_iccpr,c_disinfo_iccpr_crisis,c_disinfo_iccpr_digi,c_disinfo_noniccpr,c_disinfo_noniccpr_crisis,c_disinfo_noniccpr_digi,c_express_iccpr,c_express_iccpr_crisis,c_express_iccpr_digi,c_express_iccpr_govoff,c_express_noniccpr,c_express_noniccpr_crisis,c_express_noniccpr_digi,c_malinfo_gen,c_malinfo_gen_crisis,c_malinfo_gen_digi,c_misinfo_gen,c_misinfo_gen_crisis,c_misinfo_gen_digi,c_misinfo_iccpr,c_misinfo_iccpr_crisis,c_misinfo_iccpr_digi,c_misinfo_noniccpr,c_misinfo_noniccpr_crisis,c_misinfo_noniccpr_digi,exemption_leg,exemption_leg_crisis,exemption_sepleg,exemption_sepleg_crisis,gov_censor,gov_censor_crisis,gov_nowarrant,gov_nowarrant_crisis,gov_oversight,gov_oversight_crisis,gov_regulator,gov_regulator_crisis,gov_warrant,gov_warrant_crisis,im_correct,...,p_disinfo_iccpr_crisis,p_disinfo_iccpr_digi,p_disinfo_noniccpr,p_disinfo_noniccpr_crisis,p_disinfo_noniccpr_digi,p_express_iccpr,p_express_iccpr_crisis,p_express_iccpr_digi,p_express_noniccpr,p_express_noniccpr_crisis,p_express_noniccpr_digi,p_malinfo_gen,p_malinfo_gen_crisis,p_malinfo_gen_digi,p_misinfo_gen,p_misinfo_gen_crisis,p_misinfo_gen_digi,p_misinfo_iccpr,p_misinfo_iccpr_crisis,p_misinfo_iccpr_digi,p_misinfo_noniccpr,p_misinfo_noniccpr_crisis,p_misinfo_noniccpr_digi,reg_rules,reg_rules_crisis,source_dataset,case_name,case_id,decision_date_raw,decision_direction,judicial_body,type_of_law,theme,mode_of_expression,case_status,case_significance,case_number,ruling_judge,ruling_judge_status,ruling_judge_evidence,summary_outcome,facts,decision_overview,corresponding_law_reference,authorities,decision_cited_in,related_text,source_url,case_id_words,_merge,country_clean,country_name,country_text_id,country_id,v2x_polyarchy,v2x_freexp_altinf,v2x_freexp,v2x_jucon,v2jureform,v2jupurge,v2jupoatck,v2jupack,v2juaccnt,v2jucorrdc,v2juhcind,v2juncind,v2juhccomp,v2jucomp,v2jureview,vdem_matched,v2x_polyarchy_lag1,v2x_freexp_altinf_lag1,v2x_freexp_lag1,v2x_jucon_lag1,v2jureform_lag1,v2jupurge_lag1,v2jupoatck_lag1,v2jupack_lag1,v2juaccnt_lag1,v2jucorrdc_lag1,v2juhcind_lag1,v2juncind_lag1,v2juhccomp_lag1,v2jucomp_lag1,v2jureview_lag1,v2x_polyarchy_lag2,v2x_freexp_altinf_lag2,v2x_freexp_lag2,v2x_jucon_lag2,v2jureform_lag2,v2jupurge_lag2,v2jupoatck_lag2,v2jupack_lag2,v2juaccnt_lag2,v2jucorrdc_lag2,v2juhcind_lag2,v2juncind_lag2,v2juhccomp_lag2,v2jucomp_lag2,v2jureview_lag2
0,518,Angola,AGO,2015,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,old_judicial_decisions,NaN,Angola_2015_01,28-May-15,Contracts Expression,First Instance Court,Criminal Law,Content Regulation / Censorship|Defamation / R...,Books / Plays,NaN,NaN,NaN,NaN,not_found,NaN,Journalist Rafael Marques de Morais published ...,Rafael Marques de Morais is an Angolan investi...,"In May 2015, the Provincial Court of Luanda <a...",NaN,NaN,NaN,NaN,NaN,journalistrafaelmarquesdemoraispublishedabooka...,Matched (3),Angola,Angola,AGO,104.0,0.290,0.370,0.380,0.216,-0.157,-0.634,0.995,0.743,-0.726,-0.915,-1.210,0.217,-1.236,-1.067,1.462,True,0.290,0.370,0.380,0.216,-0.157,-0.702,0.995,0.743,-0.726,-0.915,-1.210,0.217,-1.236,-1.067,1.462,0.290,0.370,0.380,0.216,-0.157,-0.702,0.995,0.743,-0.726,-0.915,-1.210,0.217,-1.236,-1.067,1.462
1,519,Angola,AGO,2016,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,old_judicial_decisions,NaN,Angola_2016_01,28-Mar-16,Contracts Expression,First Instance Court,Criminal Law,Defamation / Reputation|Freedom of Association...,Public Speech,NaN,NaN,NaN,JanuÃ¡rio Domingos,found,"""Justice JanuÃ¡rio Domingos delivered the opin...","In March 2016, the ProvincialÂ Court of Luanda...","<p style=""line-height: 18.0pt;""><span style=""f...","On March 28, 2016, Justice JanuÃ¡rio Domingos ...",NaN,NaN,NaN,NaN,NaN,inmarchtheprovincialcourtofluandaangolafoundyo...,Matched (3),Angola,Angola,AGO,104.0,0.290,0.373,0.390,0.216,-0.157,-0.634,1.039,0.743,-0.726,-0.915,-1.210,0.217,-1.236,-1.067,1.462,True,0.290,0.370,0.380,0.216,-0.157,-0.634,0.995,0.743,-0.726,-0.915,-1.210,0.217,-1.236,-1.067,1.462,0.290,0.370,0.380,0.216,-0.157,-0.702,0.995,0.743,-0.726,-0.915,-1.210,0.217,-1.236,-1.067,1.462
2,629,Australia,AUS,1994,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,old_judicial_decisions,NaN,Australia_1994_01,12-Oct-94,Mixed Outcome,Constitutional Court,Constitutional Law,Defamation / Reputation,Press / Newspapers,NaN,NaN,NaN,NaN,not_found,the four-judge majority was formed by a joint ...,The High Court of Australia inferred an implie...,"The plaintiff, Dr Andrew Theophanous, was an M...","On October 12, 1994 the High Court handed down...",NaN,NaN,NaN,NaN,NaN,thehighcourtofaustraliainferredanimpliedrightt...,Matched (3),Australia,Australia,AUS,67.0,0.889,0.964,0.975,0.990,0.713,2.610,0.818,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835,True,0.890,0.964,0.975,0.990,0.713,2.610,0.818,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835,0.892,0.964,0.975,0.990,0.713,2.610,0.818,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835
3,633,Australia,AUS,1998,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,old_judicial_decisions,NaN,Australia_1998_01,28-Sep-98,Contracts Expression,Appellate Court,Civil Law|Constitutional Law,Artistic Expression|Defamation / Reputation,Audio / Visual Broadcasting,NaN,NaN,NaN,NaN,not_found,The Chief Justice delivered the opinion of the...,"<span style=""font-weight: 400;"">The Queensland...","<span style=""font-weight: 400;"">On September 1...","<span style=""font-weight: 400;"">The Chief Just...",NaN,NaN,NaN,NaN,NaN,thequeenslandcourtofappealdismissedtheaustrali...,Matched (3),Australia,Australia,AUS,67.0,0.882,0.964,0.975,0.990,0.713,2.610,1.174,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835,True,0.882,0.964,0.975,0.990,0.713,2.610,0.640,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835,0.891,0.964,0.975,0.990,0.713,2.610,0.732,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835
4,639,Australia,AUS,2004,0.0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,old_judicial_decisions,NaN,Australia_2004_01,6-Feb-04,Expands Expression,Appellate Court,Civil Law|Law of Evidence,Defamation / Reputation,Non-verbal Expression|Press / Newspapers,NaN,NaN,NaN,Justice French J.,found,Justice French J. delivered the opinion of the...,"<span style=""font-weight: 400;"">The Federal Co...","<span style=""font-weight: 400;"">On September 6...","<span style=""font-weight: 400;"">Justice French...",NaN,NaN,NaN,NaN,NaN,thefederalcourtofaustraliaheldbyamajoritythatt...,Matched (3),Australia,Australia,AUS,67.0,0.879,0.965,0.973,0.990,0.713,2.610,1.174,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835,True,0.879,0.965,0.973,0.990,0.713,2.610,1.174,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835,0.879,0.965,0.973,0.990,0.713,2.610,1.174,1.834,2.412,2.332,3.037,3.014,3.127,2.763,1.835

In [5]:
ls = pd.read_csv("../data/raw/ls.csv")

print(ls.shape)
ls.head()

(225, 2)

          country legal_system
0           India       Common
1   United States       Common
2        Tanzania       Common
3  United Kingdom       Common
4          Canada       Common

In [6]:
print(ls.columns)
print(df.columns)

Index(['country', 'legal_system'], dtype='object')
Index(['v1', 'country', 'iso3', 'year', 'de_jure', 'weighted_de_jure',
       'pos_total', 'neg_total', 'de_jure_count_c', 'de_jure_count_govprot',
       ...
       'v2jupurge_lag2', 'v2jupoatck_lag2', 'v2jupack_lag2', 'v2juaccnt_lag2',
       'v2jucorrdc_lag2', 'v2juhcind_lag2', 'v2juncind_lag2',
       'v2juhccomp_lag2', 'v2jucomp_lag2', 'v2jureview_lag2'],
      dtype='object', length=264)

In [7]:
df["country"] = df["country"].astype(str).str.strip()
ls["country"] = ls["country"].astype(str).str.strip()

In [8]:
df = df.merge(
    ls[["country", "legal_system"]],
    on="country",
    how="left",
    validate="many_to_one"
)

In [9]:
print(df.shape)
print("Missing legal_system:", df["legal_system"].isna().sum())
print(df["legal_system"].value_counts(dropna=False).head(20))

(1077, 265)
Missing legal_system: 2
legal_system
Common    480
Civil     309
Mixed     286
NaN         2
Name: count, dtype: int64

In [10]:
df.loc[df["legal_system"].isna(), "country"].drop_duplicates().tolist()

['European Union']

In [11]:
df.loc[df["country"] == "European Union", "legal_system"] = "Mixed"

In [12]:
print("Missing legal_system:", df["legal_system"].isna().sum())
print(df["legal_system"].value_counts(dropna=False))

Missing legal_system: 0
legal_system
Common    480
Civil     309
Mixed     288
Name: count, dtype: int64

In [13]:
output_path = "../data/processed/cases.csv"
df.to_csv(output_path, index=False)
print("Saved to:", output_path)

Saved to: ../data/processed/cases.csv